// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/autoresearch-variants/Brutalist.tsx": () => import("../components/mockups/autoresearch-variants/Brutalist.tsx"),
  "./components/mockups/autoresearch-variants/Maximalist.tsx": () => import("../components/mockups/autoresearch-variants/Maximalist.tsx"),
  "./components/mockups/autoresearch-variants/Minimal.tsx": () => import("../components/mockups/autoresearch-variants/Minimal.tsx")
};
